name: Deploy to VPS

on:
    push:
        branches:
            - dev # later, change to main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            -   name: "Get latest NixOS configuration"
                uses: actions/checkout@v4

            -   name: "Clean /proud directory on remote"
                uses: appleboy/ssh-action@v1.2.0
                with:
                    host: ${{ secrets.SSH_HOST }}
                    username: ${{ secrets.SSH_USERNAME }}
                    key: ${{ secrets.SSH_KEY }}
                    script: |
                        rm -rf /proud/*
                        mkdir -p /proud

            -   name: "Deploy app to remote"
                uses: appleboy/scp-action@v0.1.7
                with:
                    host: ${{ secrets.SSH_HOST }}
                    username: ${{ secrets.SSH_USERNAME }}
                    key: ${{ secrets.SSH_KEY }}
                    source: "."
                    target: "/proud"
                    timeout: 60s